In [1]:
# 1. Импортировать NumPy
import numpy as np

In [ ]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)

# 1.2 найти среднее значение всех элементов массива

# 1.3 найти среднее значение всех элементов для каждой строки   np.mean()
# и добавить как новый столбец

# 1.4 найти сумму значение всех элементов для каждого столбца   np.sum()
# и добавить как новую строку, учитывая результат 1.3

In [2]:
np.random.seed(5)#создаем мматрицу
arr = np.random.randint(1,100,(10,10))
arr = arr.astype(np.int64)
print(f"Массив:\n {arr}")

Массив:
 [[79 62 17 74  9 63 28 31 81  8]
 [77 16 54 81 28 45 78 76 66 48]
 [31 85 87 19 10 42 63  2 83 17]
 [79  6 59  1 81  5 37 52 28 32]
 [ 3 69 39 84 20 19  8 31 63 12]
 [68 66 56  4 92 79 28 30 34 90]
 [86  8 17 95 15 91 32 10 39 48]
 [17  6 35 46 60 25 14 32 33 77]
 [45  6 15 48 95 83  1  8 87 17]
 [65  9 91 45 38 95 76  6 23 53]]


In [3]:
arr_mean = np.mean(arr)#ищем среднее значение всех элемнтов матрицы
print(f'Среднее значание всех элементов массива : {arr_mean}')

Среднее значание всех элементов: 44.27


In [4]:
arr_mean_str = arr.mean(axis=1) #построчное среднее значение всех элемнтов матрицы
arr_mean_str

array([45.2, 56.9, 43.9, 38. , 34.8, 54.7, 44.1, 34.5, 40.5, 50.1])

In [18]:
p = np.reshape(arr_mean_str,(10,1))
arr_hst = np.hstack((arr,p))
arr_hst

array([[79. , 62. , 17. , 74. ,  9. , 63. , 28. , 31. , 81. ,  8. , 45.2],
       [77. , 16. , 54. , 81. , 28. , 45. , 78. , 76. , 66. , 48. , 56.9],
       [31. , 85. , 87. , 19. , 10. , 42. , 63. ,  2. , 83. , 17. , 43.9],
       [79. ,  6. , 59. ,  1. , 81. ,  5. , 37. , 52. , 28. , 32. , 38. ],
       [ 3. , 69. , 39. , 84. , 20. , 19. ,  8. , 31. , 63. , 12. , 34.8],
       [68. , 66. , 56. ,  4. , 92. , 79. , 28. , 30. , 34. , 90. , 54.7],
       [86. ,  8. , 17. , 95. , 15. , 91. , 32. , 10. , 39. , 48. , 44.1],
       [17. ,  6. , 35. , 46. , 60. , 25. , 14. , 32. , 33. , 77. , 34.5],
       [45. ,  6. , 15. , 48. , 95. , 83. ,  1. ,  8. , 87. , 17. , 40.5],
       [65. ,  9. , 91. , 45. , 38. , 95. , 76. ,  6. , 23. , 53. , 50.1]])

In [21]:
arr_summ_str = arr_hst.sum(axis=0)
arr_summ_str

array([550. , 333. , 470. , 497. , 448. , 547. , 365. , 278. , 537. ,
       402. , 442.7])

In [23]:
arr_summ_str = arr_summ_str.T
total = np.vstack((arr_hst,arr_summ_str))
print(total)

[[ 79.   62.   17.   74.    9.   63.   28.   31.   81.    8.   45.2]
 [ 77.   16.   54.   81.   28.   45.   78.   76.   66.   48.   56.9]
 [ 31.   85.   87.   19.   10.   42.   63.    2.   83.   17.   43.9]
 [ 79.    6.   59.    1.   81.    5.   37.   52.   28.   32.   38. ]
 [  3.   69.   39.   84.   20.   19.    8.   31.   63.   12.   34.8]
 [ 68.   66.   56.    4.   92.   79.   28.   30.   34.   90.   54.7]
 [ 86.    8.   17.   95.   15.   91.   32.   10.   39.   48.   44.1]
 [ 17.    6.   35.   46.   60.   25.   14.   32.   33.   77.   34.5]
 [ 45.    6.   15.   48.   95.   83.    1.    8.   87.   17.   40.5]
 [ 65.    9.   91.   45.   38.   95.   76.    6.   23.   53.   50.1]
 [550.  333.  470.  497.  448.  547.  365.  278.  537.  402.  442.7]]


### 2. Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули.

In [34]:
arr_diag = np.diag(range(1,8))
arr_diag

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

### 3. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3 и 5 колонки

In [38]:
np.random.seed(5)
arr3 = np.random.randint(1,100,(5,7))
arr3

array([[79, 62, 17, 74,  9, 63, 28],
       [31, 81,  8, 77, 16, 54, 81],
       [28, 45, 78, 76, 66, 48, 31],
       [85, 87, 19, 10, 42, 63,  2],
       [83, 17, 79,  6, 59,  1, 81]])

In [39]:
arr3[:,(3,5)] = arr3[:,(5,3)]
arr3

array([[79, 62, 17, 63,  9, 74, 28],
       [31, 81,  8, 54, 16, 77, 81],
       [28, 45, 78, 48, 66, 76, 31],
       [85, 87, 19, 63, 42, 10,  2],
       [83, 17, 79,  1, 59,  6, 81]])