In [2]:
import numpy as np

__Задача 1__

Напишите функцию, которая находит сумму четных элементов на главной 
диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). 
Если чётных элементов нет, то вывести 0

__Задача 2__

Решить задачи при условии, что массив может быть любой размерности:

2.1 Заменить максимальный элемент массива на 1000. (Повторяющихся максимальных элементов нет)    
2.2 Заменить минимальный элемент массива на 0. (Повторяющиеся минимальные элементы есть, поэтому нужно заменить все)

In [3]:
n=5
np.random.seed(10)
arr = np.random.randint(1,100,(n,n))
arr

array([[10, 16, 65, 29, 90],
       [94, 30,  9, 74,  1],
       [41, 37, 17, 12, 55],
       [89, 63, 34, 73, 79],
       [50, 52, 55, 78, 70]])

In [5]:
def calc_sum(some_arr):
    diag = np.diag(arr)#получаем вектор сткроку со значениями диагонали
    numb = diag[np.diag(arr)%2 == 0] #применяем булево индексирование
    c_s = np.sum(numb)
    return c_s

In [6]:
calc_sum(arr)

110

### Задача 2.1

In [16]:
c=5
r=3
arr_data = np.random.randint(1,300,(c,r))
arr_2 = np.unique(arr_data).reshape(c,r)
print(arr_2)

[[ 16  30  38]
 [ 39  50  56]
 [ 67  75 131]
 [160 206 210]
 [226 249 269]]


In [18]:
max_value = np.max(arr_2)
max_value

269

In [26]:
mask_max = arr_2 == max_value
mask_max

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [37]:
arr2_ex = np.where(mask_max,1000,arr_2)
arr2_ex

array([[  16,   30,   38],
       [  39,   50,   56],
       [  67,   75,  131],
       [ 160,  206,  210],
       [ 226,  249, 1000]])

### Задача 2.2

In [28]:
c=5
r=3
arr3 = np.random.randint(1,300,(c,r))
arr3

array([[267, 248,  12],
       [211, 163, 120],
       [140,  47, 165],
       [ 64, 248,   4],
       [ 60, 250, 163]])

In [32]:
min_value = np.min(arr3)
min_value

4

In [34]:
mask_min = arr3 == min_value
mask_min

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [40]:
arr3_ex = np.where(mask_min,0,arr3)
arr3_ex

array([[267, 248,  12],
       [211, 163, 120],
       [140,  47, 165],
       [ 64, 248,   0],
       [ 60, 250, 163]])